- app/views/userGuide/usingTheScalatestMavenPlugin.scala.html
Added spanScaleFactor to maven plugin page.
> spanScaleFactor

- app/views/releaseNotes/v300.scala.html
Added Position, custom Prettifier and RecoverMethods to 3.0.0 release notes.
> 3.0.0-RC1 Release Notes Enhancement

- app/views/userGuide/usingScalatestWithSbt.scala.html
Fleshed out new using ScalaTest with SBT page.
> New - Using ScalaTest with SBT Page

- app/controllers/UserGuide.scala
- app/views/sidenav.scala.html
- app/views/userGuide/asyncTesting.scala.html
- app/views/userGuide/propertyBasedTesting.scala.html
- conf/routes
Added user guide page for asynchronous testing.
> Asynchronous Testing User Guide

- app/controllers/UserGuide.scala
- app/views/sidenav.scala.html
- app/views/userGuide/usingScalaJS.scala.html
- app/views/userGuide/usingSelenium.scala.html
- conf/routes
Added user guide page describes about using ScalaTest with Scala-js.
> Scala-js User Guide

- app/controllers/ReleaseNotes.scala
- app/views/homePage.scala.html
- app/views/releaseNotes/releaseNotesIndex.scala.html
- app/views/releaseNotes/v301.scala.html
- conf/routes
> 3.0.1 Release

- app/controllers/Application.scala
- app/controllers/ReleaseNotes.scala
- app/views/homePage.scala.html
- app/views/install.scala.html
- app/views/olderReleases.scala.html
- app/views/releaseNotes/releaseNotesIndex.scala.html
- app/views/releaseNotes/v301.scala.html
- app/views/releaseNotes/v302.scala.html
- app/views/releaseNotes/v303.scala.html
- app/views/releaseNotes/v304.scala.html
- app/views/scaladoc.scala.html
- conf/routes
Mods to pages for 3.0.1, 3.0.2, 3.0.3, 3.0.4, and the index page
> Feature update to 3.0.4

- app/controllers/Application.scala
- app/views/homePage.scala.html
- app/views/releaseNotes/v310.scala.html
- app/views/scaladoc.scala.html
changes now that we decided to do internal modularization in 3.2.0.
> Updated release notes for RC1. 

- README
- build.sbt
- conf/application.conf
- project/plugins.sbt
Added code to support publishing as local docker image.
> Docker Support

- app/Filters.scala
- app/HSTSFilter.scala
- app/ScalaTestAllowedHostsFilter.scala
- build.sbt
> Security Filters

- app/controllers/Application.scala
- app/controllers/ReleaseNotes.scala
- app/views/homePage.scala.html
- app/views/releaseNotes/releaseNotesIndex.scala.html
- app/views/releaseNotes/v309.scala.html
- app/views/releaseNotes/v313.scala.html
- app/views/releaseNotes/v314.scala.html
- app/views/releaseNotes/v321.scala.html
- app/views/releaseNotes/v322.scala.html
- conf/routes
Updated release notes, use 3.2.2 release note as the latest.
> Release Notes Update

- app/controllers/Application.scala
Changed base scala version to the latest 2.13.3.
> Scala 2.13.3

- app/controllers/Application.scala
- app/views/install.scala.html
- app/views/quickStart.scala.html
- app/views/releaseNotes/v20.scala.html
- app/views/userGuide/philosophyAndDesign.scala.html
- app/views/userGuide/selectingAStyle.scala.html
- app/views/userGuide/sharingFixtures.scala.html
- app/views/userGuide/usingAssertions.scala.html
- app/views/userGuide/usingEitherValues.scala.html
- app/views/userGuide/usingInside.scala.html
- app/views/userGuide/usingMatchers.scala.html
- app/views/userGuide/usingOptionValues.scala.html
- app/views/userGuide/usingPartialFunctionValues.scala.html
- app/views/userGuide/usingPrivateMethodTester.scala.html
- app/views/userGuide/writingYourFirstTest.scala.html
Fixed links to scaladoc on main pages
> Fix scaladoc links

- app/views/userGuide/generatorDrivenPropertyChecks.scala.html
- app/views/userGuide/propertyBasedTesting.scala.html
- app/views/userGuide/writingScalacheckStyleProperties.scala.html
This fixes scalatest/scalatest#1090
> fix doc about minSuccessful default

- app/views/about.scala.html
Added Matt Hughes to the helping list in About.
> Matt Hughes in About

- app/controllers/Application.scala
Updated SuperSafe page to use SuperSafe 1.1.12 and Scala 2.13.5.
> SuperSafe 1.1.12

- app/views/install.scala.html
Changed all http in install.scala.html to https.
> Install Page HTTPS

- app/views/install.scala.html
- build.sbt
Updated version for ECR deployment, added 3.0.0+ as supported scala version in install page.
> Deployment 210520

- app/views/install.scala.html
Updated install.scala.html to include note about scala-js project, and recommend supersafe for users of 3.x versions.
> Install Page Enhancement

- app/views/userGuide/writingScalacheckStyleProperties.scala.html
current: https://www.scalatest.org/user_guide/writing_scalacheck_style_properties
issue: https://github.com/scalatest/scalatest/issues/1735
> updated scala-check trait to extend in docs

- app/controllers/Application.scala
- app/views/gettingStartedWithFeatureSpec.scala.html
- app/views/gettingStartedWithFunSpec.scala.html
- app/views/gettingStartedWithJunit3InScala.scala.html
- app/views/gettingStartedWithJunit4InScala.scala.html
- app/views/gettingStartedWithTestngInScala.scala.html
Get example codes and commands in getting started guide for style traits, JUnit 4, JUnit 3 and TestNG updated with latest changes.
> Getting Started Guide Fix

- app/views/plus/easymockVersions.scala.html
- app/views/plus/jmockVersions.scala.html
- app/views/plus/junitVersions.scala.html
- app/views/plus/mockitoVersions.scala.html
- app/views/plus/scalacheckVersions.scala.html
- app/views/plus/seleniumVersions.scala.html
- app/views/plus/testngVersions.scala.html
Added the missing versions for versions pages of ScalaTest+ modules.
> ScalaTest Plus Versions

- app/views/userGuide/sharingFixtures.scala.html
Fixed outdated documentation in Sharing Fixtures page.
> Sharing Fixtures Page Fix

- app/views/userGuide/propertyBasedTesting.scala.html
- app/views/userGuide/tableDrivenPropertyChecks.scala.html
- app/views/userGuide/writingScalacheckStyleProperties.scala.html
Fixed out-dated contents in property-driven test pages.
> Fix Property Test Pages

- app/controllers/Application.scala
- app/views/index.scala.html
- app/views/install.scala.html
- app/views/quickStart.scala.html
Fixed out-dated contents in home, quick start and install page.
> Fix Welcoming Pages

- app/views/userGuide/writingYourFirstTest.scala.html
Fixed out-dated contents in writing your first test page.
> Fix Write Your First Test Page

- app/views/userGuide/usingMatchers.scala.html
Fixed outdated content in using matchers user guide.
> Fix Using Matchers User Guide Page

- app/views/userGuide/usingTheScalatestMavenPlugin.scala.html
Updated using scalatest-maven-plugin to version 2.1.0.
> ScalaTest Maven Plugin 2.1.0

- app/views/main.scala.html
- public/javascripts/gtag.js
Switched to use gtag for google analytics.
> Google Analytics GTAG

- app/views/about.scala.html
Updated About page with new contributors, supporting projects and build instructions.
> About Page Update

- build.sbt
Changed heap size to 64-128mb.
> Optimal Heap Size

- build.sbt
- project/plugins.sbt
- test/ExampleUnitSpec.scala
- test/IntegrationSpec.scala
- Scala 2.13.9.
- Play 2.8.16
- ScalaTest + Play 5.0.0.
> Versions Upgrade

- app/views/userGuide/usingTheScalatestMavenPlugin.scala.html
Added documentation for the new suiteSorting and threadCount configuration option in scalatest-maven-plugin page for version 2.2.0.
> ScalaTest Maven Plugin New Configuration for v2.2.0

- app/controllers/Application.scala
- build.sbt
- project/plugins.sbt
Updated scala 2.13.10, play 2.8.17 and base scala version used in documentation to 2.13.10.
> Multiple Versions Upgrade

- app/views/userGuide/propertyBasedTesting.scala.html
Added some guide about setting initial seed in property-based testing page.
> Setting Initial Seed for Property-based Testing

- app/views/userGuide/usingTheRunner.scala.html
Added -S to using the runner user guide page.
> -S in Runner User Guide

- app/controllers/UserGuide.scala
- app/views/sidenav.scala.html
- app/views/userGuide/usingAssertions.scala.html
- app/views/userGuide/usingExpectations.scala.html
- conf/routes
- project/plugins.sbt
Added new user guide about using expectations.
> Using Expectations User Guide

- app/controllers/Application.scala
- app/views/plus/junit5.scala.html
- app/views/userGuide/runningYourTests.scala.html
Added documentation for steps to run ScalaTest with Gradle.
> Running with Gradle Docs

- app/views/index.scala.html
Fixed scala major version for scala-xml jar file name in index.scala.html.
> Landing Page Scala XML Major Scala Version Fix

- app/controllers/UserGuide.scala
- app/views/userGuide/runningYourTests.scala.html
- app/views/userGuide/usingScalaTestWithMill.scala.html
- conf/routes
Added a page about running scalatest with Mill.
> Running with Mill

- app/controllers/Application.scala
Updated latest mockito version to 5-8.
> Mockito 5.8

- project/plugins.sbt
Updated to use Play Framework 3.0.1.
> Play Framework 3.0.1

- README.md
Adjusted README.md to push to artimahub packages.
> Push to ArtimaHub Packages

- app/views/index.scala.html
- app/views/userGuide/usingTheRunner.scala.html
Updated the quick start guide command for Scala 3 on the main page and runner page.
> Quick Start Guide Command for Scala 3
